version: 2.1

orbs:
  cypress: cypress-io/cypress@1.28.0

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"
    resource_class: medium+

workflows:
  build-and-test:
    jobs:
      # Setup
      #  1. Install Cypress
      - cypress/install:
          name: "Setup Linux"
          yarn: true
          executor: with-chrome-and-firefox
          build: "yarn build"
          post-steps:
            - run:
                name: Print machine info ℹ️
                command: yarn cypress info

      # Run E2E tests in Chrome
      - cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          spec: cypress/integration/Answers/*
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          requires:
            - Setup Linux
